//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoAgenda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compromissos
    {
        public int ID { get; set; }
        public string Titulo { get; set; }
        public System.DateTime DataInicio { get; set; }
        public System.DateTime DataFinal { get; set; }
        public string Detalhes { get; set; }
    }
}
